# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 15MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo: bar

runtime:
  gogc: 42

rule_files: []
  # - "first.rules"
  # - "my/*.rules"

remote_write: []
  # - url: http://remote1/push
  #   name: drop_expensive
  #   write_relabel_configs:
  #     - source_labels: [__name__]
  #       regex: expensive.*
  #       action: drop
  #   oauth2:
  #     client_id: "123"
  #     client_secret: "456"
  #     token_url: "http://remote1/auth"
  #     tls_config:
  #       cert_file: valid_cert_file
  #       key_file: valid_key_file

  # - url: http://remote2/push
  #   protobuf_message: io.prometheus.write.v2.Request
  #   name: rw_tls
  #   tls_config:
  #     cert_file: valid_cert_file
  #     key_file: valid_key_file
  #   headers:
      # name: value

remote_read: []
  # - url: http://localhost:8000/
  #   read_recent: true
  #   name: pyapp
  #   enable_http2: false
  # - url: http://remote3/read
  #   read_recent: false
  #   name: read_special
  #   required_matchers:
  #     job: special
  #   tls_config:
  #     cert_file: valid_cert_file
  #     key_file: valid_key_file

scrape_configs: #[]
  - job_name: pyapp

    scrape_interval: 50s
    scrape_timeout: 5s
    scrape_protocols: ["PrometheusText0.0.4"]

    body_size_limit: 10MB
    sample_limit: 1000
    target_limit: 35
    label_limit: 35
    label_name_length_limit: 210
    label_value_length_limit: 210

    metrics_path: /
    scheme: http
    static_configs:
      - targets: ['pyapp:8000']


alerting:
  alertmanagers: []


# storage:
#   tsdb:
#     out_of_order_time_window: 30m

# tracing:
#   endpoint: "localhost:4317"
#   client_type: "grpc"
#   headers:
#     foo: "bar"
#   timeout: 5s
#   compression: "gzip"
#   tls_config:
#     cert_file: valid_cert_file
#     key_file: valid_key_file
#     insecure_skip_verify: true